# DVC Pipeline Configuration
stages:
  data_ingestion:
    cmd: python src/ingestion/unified_ingestion.py
    deps:
      - src/ingestion/
      - config/config.yaml
    outs:
      - data/raw/huggingface/
      - data/raw/kaggle/
    metrics:
      - metrics/ingestion_metrics.json

  data_validation:
    cmd: python src/validation/data_validator.py
    deps:
      - data/raw/
      - src/validation/
    outs:
      - data/validated/
    metrics:
      - metrics/validation_metrics.json

  data_preprocessing:
    cmd: python src/preprocessing/data_preprocessor.py
    deps:
      - data/validated/
      - src/preprocessing/
    outs:
      - data/processed/
    metrics:
      - metrics/preprocessing_metrics.json

  feature_engineering:
    cmd: python src/transformation/feature_engineer.py
    deps:
      - data/processed/
      - src/transformation/
    outs:
      - data/transformed/
    metrics:
      - metrics/feature_metrics.json

  model_training:
    cmd: python src/models/train_model.py
    deps:
      - data/transformed/
      - src/models/
    outs:
      - models/
    metrics:
      - metrics/model_metrics.json
