# Simple settings for our churn prediction project

# Where to get data from
kaggle_dataset: "blastchar/telco-customer-churn"
kaggle_file: "WA_Fn-UseC_-Telco-Customer-Churn.csv"

huggingface_dataset: "scikit-learn/adult-census-income"
huggingface_file: "customer_data.csv"

# Basic settings
random_seed: 42
test_size: 0.2